### ISSUE TITLE
Get Measurement Frequency

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/airgradient-homey#1]
I would suggest GET request for the sensor values every 30 seconds is fine. So far we haven't made that user configurable as the payload is very small and wont affect network performance.

**Comment by gslender** [comment]
I have made the polling settings within the device configurable as per this...

<img width="525" alt="image" src="https://github.com/user-attachments/assets/06132367-3f02-49b0-922e-c87d333367dc">

**Comment by gslender** [comment]
I'll close this unless there is a view to make settings any different
