### ISSUE TITLE
Configuration for CO2 calibration and Cloud Connection

### ISSUE THREAD

**Issue by airgradienthq** [airgradienthq/airgradient-homey#3]
There are quite complex configuration options for specific sensor modules that can be setup on the AirGradient dashboard. 

To keep things simple now and avoid having to deal with configuration conflicts (e.g. different settings in Homey vs AirGradient dashboard), I would only suggest two additional settings in Homey:

1. Forced CO2 calibration
2. Disable communication to the AirGradient cloud

Both can be done with the following local PUT requests:

1.
`curl -X PUT -H "Content-Type: application/json" -d '{"co2CalibrationRequested":true}' http://airgradient_{{serialnr}}.local/config`

This should be a button. On click above is fired.

2.
Disable communication to AirGradient
`curl -X PUT -H "Content-Type: application/json" -d '{"postDataToAirGradient":false}' http://airgradient_{{serialnr}}.local/config`

Enable communication to AirGradient
`curl -X PUT -H "Content-Type: application/json" -d '{"postDataToAirGradient":true}' http://airgradient_{{serialnr}}.local/config`

This should be a toggle or checkbox.

Default should be enabled.

**Comment by gslender** [comment]
So the first item, Forced CO2 calibration,  is a Action/Cmd that is run at anytime - like a button on the Homey Device.

The second item, Disable communication to the AirGradient cloud, is a settings in the Device like the other settings (ie IP address etc)

Is that correct?

**Comment by airgradienthq** [comment]
Normally the Forced CO2 calibration is not meant to be run often. Just after the initial installation and in special circumstances. So I would not expose it in the normal user interface but only in the Advaned Settings.

**Comment by gslender** [comment]
>So I would not expose it in the normal user interface but only in the Advaned Settings.

That won't work. Advanced Settings are a "saved" setting, where you set it and it remains set. It is not designed for a request/action button type interface whereby you issue a command that runs and then reset ready to be run again. There is no logical part of the UI in Advanced Settings that would function that way.

So we either don't include it (if you feel running it regularly because it is shown on the device page) or we allow it to be on the device button page, but maybe include a note saying not the be run regularly??

**Comment by airgradienthq** [comment]
Let's try and implement it in the device button page with a note. How long can the note be? I can provide a text.

**Comment by gslender** [comment]
What if I put it in the Advanced Setting as "Request CO2 Calibration" as a check button or Yes/No drop down, that when saved just reverts back to off or No again, so that when you jump back into the Advanced Settings page/screen it is off or set to No and you switch it on??

**Comment by airgradienthq** [comment]
> What if I put it in the Advanced Setting as "Request CO2 Calibration" as a check button or Yes/No drop down, that when saved just reverts back to off or No again, so that when you jump back into the Advanced Settings page/screen it is off or set to No and you switch it on??

Sounds good.

**Comment by gslender** [comment]
Implemented in the new app just published https://homey.app/a/com.airgradient/test/
