### ISSUE TITLE
No reconnect

### ISSUE THREAD

**Issue by TinoS1964** [airgradienthq/airgradient-homey#4]
After a power failure my 0-1PST won’t reconnect to the homey pro (early 2023).

the only way to get it connected again is to remove it from homey and then adding it as new device.
This is a problem, because then I also have to modify all affected  flows using the outdoor unit.
IP-address of the outdoor device does not change after powerloss

**Comment by gslender** [comment]
This test version has the fix for this and will be published soon.

https://homey.app/en-au/app/com.airgradient/AirGradient/test/

**Comment by TinoS1964** [comment]
Hi Grant,

Thanks for the quick response, I will test it.

Note: the. Outdoor sensor IP-address does not change in my case after a power loss.



Groetjes,



Tino Schenk



[image]<https://112computer.com/>



’t Slaa 117

7123 CT Aalten

+31 (543) 470455



[image]<https://112computer.com/>   [image] <https://www.linkedin.com/in/tino-schenk-525a7126/>

________________________________

**Comment by TinoS1964** [comment]
The test version did the job.

Keep up the good work 👍
